baseURL = 'https://sutrannu.github.io/sunday-raceday/'
languageCode = 'en-us'
title = 'Sunday Raceday'
theme = 'ananke'
[params.meta]
  favicon = false

[[params.ananke_socials]]
name = "discord"
url = "https://t.co/uQa7fOuaKp"