baseURL = 'https://sutrannu.github.io/sunday-raceday/'
languageCode = 'en-us'
title = 'Sunday RaceDay'
theme = 'ananke'
[params]
  favicon = "/sunday-raceday/images/logo.png"
  custom_css = ["css/race.css"]
[params.meta]
  favicon = false
[[params.ananke_socials]]
  name = "Discord"
  url = "https://t.co/uQa7fOuaKp"
